repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.0.0
    hooks:
      - id: sync_with_poetry

  # ruff - lint and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes ]
      - id: ruff-format
