[[remotes]]
name = "origin"
url = "git@github.com:turran/git-upstream-workflow.git"

[target]
remote = "origin"
branch = "final"

[source]
remote = "origin"
branch = "example1-main"

[[features]]
remote = "origin"
name = "example1-feature1"
status = "merging"

[[features]]
remote = "origin"
name = "example1-feature2"
status = "pending"
