name: Format

on:
  pull_request:
    branches:
      - '**'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Format checj
        uses: pre-commit/action@v3.0.1
